INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'SAN JOSE', 95116, '1102 E Santa Clara St', 10, 'East San Jose Carnegie Branch Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'SAN JOSE', 95112, '491 E Empire St', 10, 'Joyce Ellington Branch Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'SAN JOSE', 95113, '360 N 1st St', 10, 'Santa Clara County Law Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'SAN JOSE', 95110, '921 S 1st St', 10, 'Biblioteca Latinoamericana Branch Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'SAN JOSE', 95112, '150 E San Fernando St', 10, 'Dr.Martin Luther King,Jr.Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'SAN Francisco', 94102, '450 Golden Gate Ave', 10, 'United Staes District Ct Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'SAN Francisco', 94103, 'Lafayette St', 10, 'XVX999');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'SAN Francisco', 94103, '301 8th St #215', 10, 'Prelinger Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'SAN Francisco', 94103, '84 4th St', 10, 'City College of San Francisco Downtown Center Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'SAN Francisco', 94103, '1145 Market St', 10, 'San Francisco Law Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'Los Angeles', 90012, '313 N Figueroa St', 10, 'Public Health Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'Los Angeles', 90071, '445 S Figueroa St', 10, 'DexProtector');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'Los Angeles', 90015, '919 S Grand Ave', 10, 'FIDM Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'Los Angeles', 90012, '639 N Hill St', 10, 'Chinatown Branch Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'Los Angeles', 90012, '301 W 1st St', 10, 'LA Law Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'San Diego', 92101, '1350 El Prado', 10, 'Museum of Man Scientific Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'San Diego', 92101, '290 Cedar St', 10, 'California Western School of Law Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'San Diego', 92101, '1313 Park Blvd', 10, 'Building L University Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'San Diego', 92102, '1811 Edgemont St', 10, 'Look Back Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('CA', 'San Diego', 92134, '34950 Bob Wilson Dr', 10, 'Maval Medical Center Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Kirkland', 98033, '308 Kirkland Ave', 10, 'Kirkland Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Kirkland', 98033, '5530 110th Ln NE', 10, 'Hurst Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Kirkland', 98034, '8605 NE 139th St', 10, 'Little Free Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Kirkland', 98034, '12315 NE 143 rd St', 10, 'Kingsgate Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Kirkland', 98034, '11605 132nd Ave NE', 10, 'Lake Washington Institute of Technology');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Redmond', 98052, '14780 NE 95th St', 10, 'Christian Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Redmond', 98052, '15990 NE 85th St', 10, 'Redmond Regional Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Redmond', 98053, '20301 NE 108th St', 10, 'Overlake School Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Redmond', 98053, '10735 Cedar Park Cres NE', 10, 'Redmond Ridge Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Redmond', 98052, '7725 188th Ave NE', 10, 'Redmond Costco');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Bellevue', 98004, '9829 NE 5th St', 10, 'Little Free Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Bellevue', 98004, '10675 NE 20th St', 10, 'Family History Center');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Bellevue', 98008, '15600 NE 8th St', 10, 'Crossroads Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Bellevue', 98007, '15590 Lake Hills Blvd', 10, 'Lake Hills Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Bellevue', 98005, '100 140th Ave SE', 10, 'Sammamish High School');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Seattle', 98101, '1300 1st Ave', 10, 'Seattle Art Museum');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Seattle', 98121, '2021 9th Ave', 10, 'Washington Talking Book Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Seattle', 98101, '925 Seneca St', 10, 'Virginia Mason Med Center Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Seattle', 98104, '516 3rd Ave', 10, 'King Country Law Library');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('WA', 'Seattle', 98101, '1200 6th Ave', 10, 'Region 10 Library');


INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('TX', 'Kerrville', 78028, '505 Water St', 10, 'Butt-Holdsworth');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('TX', 'Kerrville', 78028, '425 Water St', 10, 'Kerr Regional History Center');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('TX', 'Allen', 75013, '300 N Allen Dr', 10, 'Allen Public ');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('TX', 'Keller', 76248, '640 Johnson Rd', 10, 'Keller Public');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('TX', 'Lubbock', 79401, '1306 9th St', 10, 'West Texas');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('TX', 'Schertz', 78154, '798 Schertz Pkwy', 10, 'Schertz');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('TX', 'Taylor', 76574, '801 Vance St', 10, 'Taylor Public ');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('TX', 'Toyahvale,', 79786, '9207 TX-17', 10, 'Balmorhea');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('TX', 'Austin',78752, '1420 E Anderson Ln', 10, 'Signature Austin');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('TX', 'Austin',78753, '9414 N Lamar Blvd', 10, 'H-E-B');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('FL', 'Bartow,', 33830, '2150 S Broadway Ave', 10, 'Bartow Public');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('FL', 'Brooksville', 34601, '238 Howell Ave', 10, 'Hernando');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('FL', 'Palm Springs', 33461, '217 Cypress Ln', 10, 'Palm Springs Public');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('FL', 'Orlando', 32821, '8788 Vineland Ave', 10, 'Vineland');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('FL', 'Ruskin', 33570, '402 S Tamiami Trail,', 10, 'Chevron');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('FL', 'Wildwood', 34785, '753 FL-44', 10, 'Sunoco');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('FL', 'Boynton', 33436, '9094 S Military Trail', 10, 'Orion');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('FL', 'Pompano', 33069, '1493 NW 31st Ave', 10, 'AMERIKA');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('FL', 'Florida', 35426 , 'S Dixie Hwy', 10, 'RaceTrac');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('FL', 'Okeechobee', 34972, '184 Floridas Turnpike', 10, 'Yeehaw');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'NEW YORK', 10010, '2430 FDR Dr', 10, 'NEW YORK BP');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'NEW YORK', 10014, '51-63 8th Ave', 10, 'NEW YORK LIBERTY');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY','NEW YORK',10019, '718 11th Ave', 10, 'NEW YORK BISMA');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY','NEW YORK',10025, '303 W 96th St', 10, 'NEW YORK 315 W 96');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY','NEW YORK',10032, '3740 Broadway', 10, 'NEW YORK BROADWAY');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'BUFFALO', 14203, '1 Lafayette Square', 10, 'Buffalo & Erie');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'BUFFALO', 14208, '1324 Jefferson Ave', 10, 'Buffalo Frank E');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'BUFFALO', 14222, '1300 Elmwood Ave', 10, 'Buffalo E. H. Butler');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'BUFFALO', 14216, '975 Hertel Ave', 10, 'Buffalo North Park');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'BUFFALO', 14215, '1187 E Delavan Ave', 10, 'Buffalo East Delavan');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'Albany', 12206, 'Univercity at Albany', 10, 'Albany Science');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'Albany', 12206, '28 Essex St', 10, 'Albany Upper Hudson');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'Albany', 12208, '517 Western Ave', 10, 'Albany Pine Hills');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'Albany', 12209, '331 Delaware Ave', 10, 'Albany Delaware');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'Albany', 12202, '105 Schuyler St', 10, 'Albany Howe');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'Rochester', 14606, '956 Lyell Ave', 10, 'Rochester Lyell');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'Rochester', 14616, '2808 Dewey Ave', 10, 'Rochester Barnard');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'Rochester', 14617, '1290 Titus Ave', 10, 'Rochester Irondequoit');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'Rochester', 14609, '530 Webster Ave', 10, 'Rochester Sully');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NY', 'Rochester', 14607, '809 Monroe Ave', 10, 'Rochester Monroe');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Newark', 07108, '8739 Bergen St', 10, 'Newark Clinton');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Newark', 07105, '140 Van Buren St', 10, 'Newark Van Buren');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Newark', 07103, '50 Hayes St', 10, 'Newark Springfield');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Newark', 07106, '75 Alexander St', 10, 'Newark Vailsburg');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Newark', 07104, '722 Summer Ave', 10, 'Newark North End');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Jersey City', 07304, '1017 West Side Ave', 10, 'Jersey City Marion');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Jersey City', 07304, '546 West Side Ave', 10, 'Jersey City West');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Jersey City', 07305, '275 Martin Luther King Dr.', 10, 'Jersey City Cunningham');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Jersey City', 07304, '307 Pacific Ave', 10, 'Jersey City Lafayette');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Jersey City', 07302, '326 8th St', 10, 'Jersey City Pavonia');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Trenton', 08618, '2310 Stuyvesant Ave', 10, 'Trenton North');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Trenton', 08608, '120 Academy St', 10, 'Trenton Public');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Trenton', 08619, '1 Justice Samuel A Alito Jr Way', 10, 'Trenton Hamilton');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Trenton', 08609, '1115 Greenwood Ave', 10, 'Trenton Briggs');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Trenton', 08611, '25 Market St', 10, 'Trenton Attorney');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Edison',08820, '777 Grove Ave', 10, 'Edison North');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Edison',08837, '141 Hoover Ave', 10, 'Edison Clara Barton');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Edison',08817, '340 Plainfield Ave', 10, 'Edison Main');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Edison',08837, '55 Parsonage Rd', 10, 'Edison Menlo Park');

INSERT INTO PARK_LOCATION (LOCATION_STATE,  LOCATION_CITY, LOCATION_ZIPCODE, LOCATION_STREET, LOCATION_CAPACITY, LOCATION_NAME)
VALUES('NJ', 'Edison',08820, '65 James St', 10, 'Edison JFK');



